Repository EchoesHQ/gitlab-proxy, pull requests merged in 2022-07, with the labels that each got.

#9 feat: rather include the ip restriction
  README.md
  nginx-proxy/Dockerfile
  nginx-proxy/gitlab-proxy.conf
  nginx-proxy/ip_restriction.conf
Labels: echoes/effort: XS, echoes/intent: other

#10 chore: add image build in CI
  .github/workflows/default.yml
Labels: echoes/effort: XS, echoes/intent: throughput

#12 Minor README.md edits
  README.md
Labels: echoes/effort: XS, echoes/intent: other

#11 feat: add tests
  .github/workflows/default.yml
  tests/discussions.sh
  tests/groups.sh
  tests/groups_hooks.sh
  tests/groups_labels.sh
  tests/merge_requests.sh
  tests/tags.sh
  tests/users.sh
Labels: echoes/intent: other

#14 chore(CI): rm pr target triggers
  .github/workflows/default.yml
Labels: echoes/effort: XS, echoes/intent: other

#13 feat: add more tests
  .github/workflows/default.yml
  nginx-proxy/gitlab-api-routes/groups_hooks.conf
  nginx-proxy/gitlab-api-routes/merge_requests.conf
  tests/discussions.sh
  tests/groups.sh
  tests/groups_hooks.sh
  tests/groups_labels.sh
  tests/helpers.sh
  tests/merge_requests.sh
  tests/tags.sh
  tests/users.sh
Labels: echoes/intent: other
